### PR TITLE
WIP: fix nyc config

### PR DESCRIPTION
**Pull request by JaKXz**
@danez this is what I tried locally, but is still blocked by istanbuljs/babel-plugin-istanbul#4.

### CODE REVIEW

**Comment by bcoe** [comment]
@JaKXz we finally figured out an approach to `--all` that I think works (you can see the pertinent changes on `nyc` and `istanbul-lib-instrument`).

Would love the extra help testing:

`npm cache clear; npm i nyc@next babel-plugin-istanbul@latest`.

**Comment by JaKXz** [comment]
@bcoe thanks! gave it a shot but still getting warnings from the instrumenter - I believe because of flow-type syntax. The `.babelrc` for this project seems to configured correctly though so I'm not sure what's up :|

**Comment by danez** [comment]
thanks I included this changes in master now.

**Comment by bcoe** [comment]
@danez @JaKXz nice, sounds like you got things working?

**Comment by danez** [comment]
Yes works fine.

**Pull request closed without merging**
